name: batdata
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.*
  - pandas==1.0.0
  - scipy==1.3.2
  - pytables==3.6.1
  - h5py==2.10.0
  - jupyterlab
  - matplotlib
  - flake8
  - pytest
  - tqdm
  - pip
  - pip:
    - pydantic==1.4
    - git+https://github.com/materials-data-facility/MaterialsIO.git
    - -e .  # Installs the batdata library in development mode
